name: Python application CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run migrations (optional)
        run: |
          # Замените следующую строку командой для выполнения ваших миграций, если это необходимо
          # alembic upgrade head

      - name: Run tests
        env:
          # Убедитесь, что данная переменная окружения соответствует вашей конфигурации
          POSTGRES_URL: postgresql://postgres:password@localhost:5432/postgres
        run: |
          pytest ./tests
